// <auto-generated />
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeApi.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20250707142921_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("GrossAnnualSalary")
                        .HasColumnType("float");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            FirstName = "Alice",
                            GrossAnnualSalary = 50000.0,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = "2",
                            FirstName = "Bob",
                            GrossAnnualSalary = 60000.0,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = "3",
                            FirstName = "Charlie",
                            GrossAnnualSalary = 45000.0,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = "4",
                            FirstName = "Diana",
                            GrossAnnualSalary = 70000.0,
                            LastName = "Reed"
                        },
                        new
                        {
                            Id = "5",
                            FirstName = "Ethan",
                            GrossAnnualSalary = 55000.0,
                            LastName = "Cole"
                        },
                        new
                        {
                            Id = "6",
                            FirstName = "Fiona",
                            GrossAnnualSalary = 80000.0,
                            LastName = "Black"
                        },
                        new
                        {
                            Id = "7",
                            FirstName = "George",
                            GrossAnnualSalary = 48000.0,
                            LastName = "White"
                        },
                        new
                        {
                            Id = "8",
                            FirstName = "Hannah",
                            GrossAnnualSalary = 75000.0,
                            LastName = "Green"
                        },
                        new
                        {
                            Id = "9",
                            FirstName = "Ian",
                            GrossAnnualSalary = 52000.0,
                            LastName = "Blue"
                        },
                        new
                        {
                            Id = "10",
                            FirstName = "Julia",
                            GrossAnnualSalary = 63000.0,
                            LastName = "Gray"
                        },
                        new
                        {
                            Id = "11",
                            FirstName = "Kevin",
                            GrossAnnualSalary = 47000.0,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = "12",
                            FirstName = "Laura",
                            GrossAnnualSalary = 67000.0,
                            LastName = "Wright"
                        },
                        new
                        {
                            Id = "13",
                            FirstName = "Michael",
                            GrossAnnualSalary = 53000.0,
                            LastName = "King"
                        },
                        new
                        {
                            Id = "14",
                            FirstName = "Nina",
                            GrossAnnualSalary = 49000.0,
                            LastName = "Young"
                        },
                        new
                        {
                            Id = "15",
                            FirstName = "Oscar",
                            GrossAnnualSalary = 58000.0,
                            LastName = "Hall"
                        },
                        new
                        {
                            Id = "16",
                            FirstName = "Paula",
                            GrossAnnualSalary = 76000.0,
                            LastName = "Scott"
                        },
                        new
                        {
                            Id = "17",
                            FirstName = "Quentin",
                            GrossAnnualSalary = 62000.0,
                            LastName = "Moore"
                        },
                        new
                        {
                            Id = "18",
                            FirstName = "Rachel",
                            GrossAnnualSalary = 54000.0,
                            LastName = "Clark"
                        },
                        new
                        {
                            Id = "19",
                            FirstName = "Steven",
                            GrossAnnualSalary = 47000.0,
                            LastName = "Lewis"
                        },
                        new
                        {
                            Id = "20",
                            FirstName = "Tina",
                            GrossAnnualSalary = 61000.0,
                            LastName = "Walker"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
